language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"
cache:
  apt: true
  pip: false
env: PYCURL_SSL_LIBRARY=gnutls
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - libssl1.0.0
install:
  - pip install unittest2 mock vcrpy tox-travis
  - python setup.py clean --all
  - python setup.py install
script:
  - python -W always setup.py test

