language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"
cache:
  apt: true
  pip: false
install:
  - pip install unittest2 mock vcrpy tox-travis
  - python setup.py clean --all
  - python setup.py install
script:
  - python -W always setup.py test

